#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

redirect_cmd exec s6-setuidgid hotio python "${APP_DIR}/SABnzbd.py" --browser 0 --server 0.0.0.0:8080 --config-file "${CONFIG_DIR}/app/sabnzbd.ini"
