#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 "${APP_DIR}/SABnzbd.py" --browser 0 --server 0.0.0.0:8080 --config-file "${CONFIG_DIR}/app/sabnzbd.ini" ${ARGS}
